services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    command: ["postgres", "-c", "log_statement=all"]
  redis:
    image: 'redis:latest'
  app: 
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - |
        ROCKET_DATABASES={
          pg_db={url=postgres://postgres:postgres@postgres/app_db},
          redis={url=redis://redis:6379}
        }
      - RUST_BACKTRACE=1
    volumes:
      - ./:/app/
  